/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PrestamoControlador;
import java.sql.Connection;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Prestamo;
import java.sql.*;
import utilidades.ConexionDB;

/**
 *
 * @author sarai
 */
public class HistorialPrestamo extends javax.swing.JFrame {
    

    /**
     * Creates new form VerPrestamos
     */
    public HistorialPrestamo() {
        initComponents();
        actualizarPrestamosVencidos();
        cargarTablaPrestamos();
        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void cargarTablaPrestamos() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][]{},
        new String[]{"ID","Cantidad total", "Fecha préstamo", "Fecha devolución", "Estado"}
    );
    tblPrestamo.setModel(modelo);

    try {
        Connection conn = ConexionDB.getConexion();
        String sql = "SELECT idPrestamo, cantidadTotal, fechaPrestamo, fechaDevolucion, status FROM prestamo ORDER BY fechaPrestamo DESC";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("idPrestamo"),
                    rs.getInt("cantidadTotal"),
                    rs.getDate("fechaPrestamo"),
                    rs.getDate("fechaDevolucion"),
                    rs.getString("status")
                });
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar tabla de préstamos: " + e.getMessage());
    }
}

    
    
    private void actualizarPrestamosVencidos() {
    try {
        Connection conn = ConexionDB.getConexion();
        PrestamoControlador prestamoControlador = new PrestamoControlador(conn);
        int actualizados = prestamoControlador.actualizarPrestamosAMulta();
        
        if (actualizados > 0) {
            JOptionPane.showMessageDialog(null, 
                actualizados + " préstamos han sido actualizados a 'Multa' por retraso y se generaron los datos de multa",
                "Préstamos actualizados", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, 
            "Error al actualizar préstamos vencidos: " + ex.getMessage(),
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrestamos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamo = new javax.swing.JTable();
        brnRegresar = new javax.swing.JButton();
        btnEntregado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrestamos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 142, 142), 2));
        panelPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 142));
        jLabel1.setText("Historial de prestamos");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelPrestamos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 200, -1));

        tblPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamo);

        panelPrestamos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 870, 470));

        brnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        brnRegresar.setText("Regresar");
        brnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegresarActionPerformed(evt);
            }
        });
        panelPrestamos.add(brnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        btnEntregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entregarLibro.png"))); // NOI18N
        btnEntregado.setText("Entregado");
        btnEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregadoActionPerformed(evt);
            }
        });
        panelPrestamos.add(btnEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_brnRegresarActionPerformed

    private void btnEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregadoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblPrestamo.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un préstamo");
            return;
        }
        
        try {
            Connection conn = ConexionDB.getConexion();
        PrestamoControlador prestamoControlador = new PrestamoControlador(conn);
            // Obtener el ID del préstamo (asumiendo que tienes una columna oculta con el ID)
            int idPrestamo = (int) tblPrestamo.getValueAt(filaSeleccionada, 0);
            
            if (prestamoControlador.marcarComoEntregado(idPrestamo)) {
                JOptionPane.showMessageDialog(null, "Préstamo marcado como entregado");
                cargarTablaPrestamos(); // Refrescar la tabla
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el préstamo");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEntregadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegresar;
    private javax.swing.JButton btnEntregado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrestamos;
    private javax.swing.JTable tblPrestamo;
    // End of variables declaration//GEN-END:variables
}
