/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.UsuarioControlador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Usuario;
import utilidades.ConexionDB;

/**
 *
 * @author Sarai
 */
public class IMenu extends javax.swing.JFrame {
    private String tipoUsuario;

    
    /**
     * Creates new form Principal
     */
    public IMenu(String correoUsuarioLogueado) {
        initComponents();
        verificarTipoUsuarioPorCorreo(correoUsuarioLogueado);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void verificarTipoUsuarioPorCorreo(String correo) {
    try {
        Connection conexion = ConexionDB.getConexion();
        UsuarioControlador controlador = new UsuarioControlador(conexion);
        Usuario usuario = controlador.buscarPorCorreo(correo);

        if (usuario != null) {
            this.tipoUsuario = usuario.getRol(); // Cambiado de getTipoUsuario() a getRol()

            if ("Bibliotecario".equalsIgnoreCase(tipoUsuario)) {
                MenuUsuarios.setVisible(false);
                lblUsuario.setVisible(false);
                menuDetalles.setVisible(false);
                lblDetalle.setVisible(false);
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al verificar tipo de usuario: " + e.getMessage());
        e.printStackTrace();
    }
}


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MenuLibros = new javax.swing.JButton();
        MenuMultas = new javax.swing.JButton();
        MenuUsuarios = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        MenuPrestamo1 = new javax.swing.JButton();
        lblDetalle = new javax.swing.JLabel();
        menuDetalles = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 142));
        jLabel1.setText("MENU");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, 40));

        jLabel2.setText("Libros");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel4.setText("Multas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        MenuLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.png"))); // NOI18N
        MenuLibros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 142, 142), 2));
        MenuLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(MenuLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 100));

        MenuMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multa.png"))); // NOI18N
        MenuMultas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 142, 142), 2, true));
        MenuMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMultasActionPerformed(evt);
            }
        });
        jPanel1.add(MenuMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 120, 100));

        MenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        MenuUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 142, 142), 2));
        MenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(MenuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 100));

        lblUsuario.setText("Usuarios");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 142, 142));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarSesion.png"))); // NOI18N
        jButton2.setText("Cerrar session");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 150, 30));

        MenuPrestamo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo.png"))); // NOI18N
        MenuPrestamo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 142, 142), 2));
        MenuPrestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrestamo1ActionPerformed(evt);
            }
        });
        jPanel1.add(MenuPrestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 120, 100));

        lblDetalle.setText("Prestamos detallados");
        jPanel1.add(lblDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        menuDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verPrestamo.png"))); // NOI18N
        menuDetalles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 142, 142), 2));
        menuDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(menuDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, 100));

        jLabel6.setText("Prestamo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MenuLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLibrosActionPerformed
        // TODO add your handling code here:
        VerLibros verLib = new VerLibros(tipoUsuario); 
        verLib.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        verLib.addWindowListener(new WindowAdapter() {
        });
       verLib.setVisible(true);
    }//GEN-LAST:event_MenuLibrosActionPerformed

    private void MenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosActionPerformed
        // TODO add your handling code here:
        VerUsuarios verUser= new VerUsuarios();
        verUser.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        verUser.addWindowListener(new WindowAdapter() {
        });
       verUser.setVisible(true);
    }//GEN-LAST:event_MenuUsuariosActionPerformed

    private void MenuMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMultasActionPerformed
        // TODO add your handling code here:
        HistorialMulta verMul= new HistorialMulta();
        verMul.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        verMul.addWindowListener(new WindowAdapter() {
        });
        
        verMul.setVisible(true);
    }//GEN-LAST:event_MenuMultasActionPerformed

    private void MenuPrestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrestamo1ActionPerformed
        // TODO add your handling code here:
        HacerPrestamo hacerPres= new HacerPrestamo();
        hacerPres.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        hacerPres.addWindowListener(new WindowAdapter() {
        });
        
        hacerPres.setVisible(true);
    }//GEN-LAST:event_MenuPrestamo1ActionPerformed

    private void menuDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDetallesActionPerformed
        // TODO add your handling code here:
        PrestamosConcretos hacerPres= new PrestamosConcretos();
        hacerPres.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        hacerPres.addWindowListener(new WindowAdapter() {
        });
        
        hacerPres.setVisible(true);
    }//GEN-LAST:event_menuDetallesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuLibros;
    private javax.swing.JButton MenuMultas;
    private javax.swing.JButton MenuPrestamo1;
    private javax.swing.JButton MenuUsuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JButton menuDetalles;
    // End of variables declaration//GEN-END:variables
}
