/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import VALIDACION.Validacion;
import utilidades.DimencionImagen;
import controlador.UsuarioControlador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import modelo.Usuario;
import java.sql.Connection;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import utilidades.ConexionDB;

/**
 *
 * @author Sarai
 */
public class VerUsuarios extends javax.swing.JFrame {
    
    /**
     * Creates new form IUsuario
     */
    public VerUsuarios() {
        initComponents();
        cargarUsuariosEnTabla();
        DimencionImagen.ajustarImagenEnLabel(lblBuscarUser, "/imagenes/buscarUser.png", 30, 30);
        configurarBarraBusqueda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void configurarBarraBusqueda() {
        // Configurar el listener para la barra de búsqueda
        barraBusqueda1.getCampoBusqueda().getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarTabla();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarTabla();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarTabla();
            }
        });
    }
    
    private void filtrarTabla() {
    String textoBusqueda = barraBusqueda1.getCampoBusqueda().getText().toLowerCase();
    DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
    modelo.setRowCount(0); // Limpiar tabla

    try {
        Connection conexion = ConexionDB.getConexion();
        UsuarioControlador controlador = new UsuarioControlador(conexion);

        for (Usuario usuario : controlador.buscarTodos()) {
            if (textoBusqueda.isEmpty()
                || usuario.getNombre().toLowerCase().contains(textoBusqueda)
                || usuario.getApellidos().toLowerCase().contains(textoBusqueda)
                || usuario.getTelefono().toLowerCase().contains(textoBusqueda)
                || usuario.getCorreo().toLowerCase().contains(textoBusqueda)
                || usuario.getRol().toLowerCase().contains(textoBusqueda)) {

                modelo.addRow(new Object[] {
                    usuario.getNombre(),
                    usuario.getApellidos(),
                    usuario.getTelefono(),
                    usuario.getCorreo(),
                    usuario.getRol()
                });
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al filtrar usuarios: " + e.getMessage());
        e.printStackTrace();
    }
}

   
    public void cargarUsuariosEnTabla() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][] {},
        new String[] { "Nombres", "Apellidos", "Teléfono", "Correo", "Rol" }
    );
    tblUser.setModel(modelo);
    modelo.setRowCount(0); // Limpiar tabla

    try {
        Connection conexion = ConexionDB.getConexion();
        UsuarioControlador controlador = new UsuarioControlador(conexion);

        for (Usuario u : controlador.buscarTodos()) {
            modelo.addRow(new Object[] {
                u.getNombre(),
                u.getApellidos(),
                u.getTelefono(),
                u.getCorreo(),
                u.getRol()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        e.printStackTrace();
    }
}

    


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUser = new javax.swing.JPanel();
        lblBuscarUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAregarU = new javax.swing.JButton();
        btnEliminarU = new javax.swing.JButton();
        btnEditarU = new javax.swing.JButton();
        barraBusqueda1 = new barrabusqueda_actualizado.barraBusqueda();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        brnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 142, 142), 2));
        panelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarUser.png"))); // NOI18N
        panelUser.add(lblBuscarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 142));
        jLabel1.setText("Usuarios");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 80, -1));

        btnAregarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnAregarU.setText("Agregar");
        btnAregarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAregarUActionPerformed(evt);
            }
        });
        panelUser.add(btnAregarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        btnEliminarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminarU.setText("Eliminar");
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });
        panelUser.add(btnEliminarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        btnEditarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditarU.setText("Editar");
        btnEditarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUActionPerformed(evt);
            }
        });
        panelUser.add(btnEditarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 101, -1));
        panelUser.add(barraBusqueda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 74, 440, -1));

        jLabel6.setText("Buscar Usuario");
        panelUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 54, -1, -1));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        panelUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 910, 330));

        brnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        brnRegresar.setText("Regresar");
        brnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegresarActionPerformed(evt);
            }
        });
        panelUser.add(brnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        getContentPane().add(panelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUActionPerformed
       int filaSeleccionada = tblUser.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona un libro para editar.");
        return;
    }

    String nombres = tblUser.getValueAt(filaSeleccionada, 0).toString();
    String apellidos = tblUser.getValueAt(filaSeleccionada, 1).toString();
    String telefono = tblUser.getValueAt(filaSeleccionada, 2).toString();
     String correo = tblUser.getValueAt(filaSeleccionada, 3).toString();
    String tipoUsuario = tblUser.getValueAt(filaSeleccionada, 4).toString();

    // Crear y mostrar FrmLibros con los datos cargados
    FrmUsuario formulario= new FrmUsuario();
    formulario.setModoEdicion(true); // opcional, si quieres un flag para saber que es edición
    formulario.setDatosUsuario(nombres, apellidos, telefono, correo, tipoUsuario);
    
        formulario.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        formulario.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // recarga combos después
                cargarUsuariosEnTabla();    
            }
        });
    
    formulario.setVisible(true);
    }//GEN-LAST:event_btnEditarUActionPerformed

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
        int filaSeleccionada = tblUser.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario en la tabla para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Connection conexion = ConexionDB.getConexion();
    UsuarioControlador controlador = new UsuarioControlador(conexion);
            // Obtén el correo desde la tabla
            String correo = (String) tblUser.getValueAt(filaSeleccionada, 3); // columna 3 = correo

            if (controlador.eliminarPorCorreo(correo)) {
                DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
                modelo.removeRow(filaSeleccionada);
                cargarUsuariosEnTabla();
                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el usuario.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarUActionPerformed

    private void btnAregarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAregarUActionPerformed
        // TODO add your handling code here:
        FrmUsuario frmUsuario = new FrmUsuario();
        frmUsuario.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmUsuario.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // recarga combos después de cerrar
                cargarUsuariosEnTabla();     // recarga autores
            }
        });
        frmUsuario.setVisible(true);
    }//GEN-LAST:event_btnAregarUActionPerformed

    private void brnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_brnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private barrabusqueda_actualizado.barraBusqueda barraBusqueda1;
    private javax.swing.JButton brnRegresar;
    private javax.swing.JButton btnAregarU;
    private javax.swing.JButton btnEditarU;
    private javax.swing.JButton btnEliminarU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarUser;
    private javax.swing.JPanel panelUser;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}
